# .github/workflows/app.yaml
name: HW1-FAST-AQ-Parser-CW

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip and install the package
        run: | 
          pip install .  

      - name: Run tests with pytest
        run: |
          python -m pytest -vv tests/*py